version: "3"
services:

  api:
    container_name: api
    build: ./api/
    volumes:
      - './api:/usr/src/'
      - './api/package.json:/usr/src/package.json'
      - '/usr/src/node_modules'
    ports:
      - '3001:3001'

  front:
    container_name: front
    build: ./front/
    volumes:
      - './front:/usr/src/'
      - './front/package.json:/usr/src/package.json'
      - '/usr/src/node_modules'
    ports:
      - '3000:3000'

  db:
    container_name: db
    image: neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_USER-neo4j}/${NEO4J_PASS-neo4j}
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
